"""
ASSET_TYPES — shared constant used by routes_research.py and admin_routes.py.
Lives here so admin_routes can import it without pulling in routes_research
(which registers @app.route decorators and cannot be imported after first request).
"""

ASSET_TYPES = {
    'stocks': {
        'name': 'Stocks',
        'title': 'Stocks Research & Signals',
        'subtitle': 'In-depth analysis and trading signals for Indian equities',
        'icon': 'fas fa-chart-bar',
        'description': 'Comprehensive research and real-time signals for NSE and BSE listed stocks.',
        'features': [
            {'icon': 'fas fa-search-dollar', 'title': 'Fundamental Analysis', 'desc': 'Deep-dive into financials, ratios, and company performance'},
            {'icon': 'fas fa-chart-line',    'title': 'Technical Signals',    'desc': 'AI-powered buy/sell signals based on chart patterns'},
            {'icon': 'fas fa-newspaper',     'title': 'Market News',          'desc': 'Real-time news and sentiment analysis'},
            {'icon': 'fas fa-bullseye',      'title': 'Price Targets',        'desc': 'AI-generated price targets with confidence levels'},
        ],
        'market_hours':   'NSE/BSE: 9:15 AM - 3:30 PM IST',
        'signal_type':    'STOCK',
        'example_symbols':'RELIANCE, TCS, INFY',
    },
    'futures': {
        'name': 'Futures',
        'title': 'Futures Research & Signals',
        'subtitle': 'Advanced analysis for Index and Stock Futures trading',
        'icon': 'fas fa-calendar-alt',
        'description': 'Professional-grade research for NIFTY, BANKNIFTY, and stock futures with expiry-based strategies.',
        'features': [
            {'icon': 'fas fa-layer-group',    'title': 'Open Interest Analysis', 'desc': 'Track OI buildup and unwinding patterns'},
            {'icon': 'fas fa-arrows-alt-v',   'title': 'Rollover Data',          'desc': 'Monthly rollover percentages and trends'},
            {'icon': 'fas fa-balance-scale',  'title': 'Basis & Premium',        'desc': 'Futures premium/discount analysis'},
            {'icon': 'fas fa-clock',          'title': 'Expiry Strategies',      'desc': 'Time-decay aware trading signals'},
        ],
        'market_hours':   'NSE F&O: 9:15 AM - 3:30 PM IST',
        'signal_type':    'FUTURES',
        'example_symbols':'NIFTY, BANKNIFTY, FINNIFTY',
    },
    'options': {
        'name': 'Options',
        'title': 'Options Research & Signals',
        'subtitle': 'Greeks-based analysis and strategy recommendations',
        'icon': 'fas fa-layer-group',
        'description': 'Sophisticated options analysis with Greeks, IV, and strategy builder for informed trading decisions.',
        'features': [
            {'icon': 'fas fa-chart-area',      'title': 'Implied Volatility', 'desc': 'IV percentile and skew analysis'},
            {'icon': 'fas fa-calculator',      'title': 'Options Greeks',     'desc': 'Delta, Gamma, Theta, Vega tracking'},
            {'icon': 'fas fa-project-diagram', 'title': 'Strategy Builder',   'desc': 'Multi-leg strategy recommendations'},
            {'icon': 'fas fa-fire',            'title': 'Max Pain Analysis',  'desc': 'Weekly max pain levels and trends'},
        ],
        'market_hours':   'NSE F&O: 9:15 AM - 3:30 PM IST',
        'signal_type':    'OPTIONS',
        'example_symbols':'NIFTY, BANKNIFTY, SENSEX',
    },
    'commodities': {
        'name': 'Commodities',
        'title': 'Commodities Research & Signals',
        'subtitle': 'MCX trading signals for Gold, Silver, Crude and more',
        'icon': 'fas fa-cubes',
        'description': 'Real-time analysis and trading signals for MCX commodities including precious metals and energy.',
        'features': [
            {'icon': 'fas fa-coins',    'title': 'Precious Metals',    'desc': 'Gold, Silver analysis with global cues'},
            {'icon': 'fas fa-oil-can',  'title': 'Energy',             'desc': 'Crude Oil, Natural Gas signals'},
            {'icon': 'fas fa-seedling', 'title': 'Agri Commodities',   'desc': 'Agricultural commodities research'},
            {'icon': 'fas fa-globe',    'title': 'Global Correlation',  'desc': 'International market linkages'},
        ],
        'market_hours':   'MCX: 9:00 AM - 11:30 PM IST',
        'signal_type':    'COMMODITY',
        'example_symbols':'GOLDM, SILVERM, CRUDEOIL',
    },
    'currency': {
        'name': 'Currency',
        'title': 'Currency Research & Signals',
        'subtitle': 'Forex analysis for INR pairs and cross-currency trading',
        'icon': 'fas fa-rupee-sign',
        'description': 'Expert analysis on USD/INR, EUR/INR and other currency pairs with RBI policy insights.',
        'features': [
            {'icon': 'fas fa-dollar-sign',  'title': 'USD/INR Focus', 'desc': 'Primary pair analysis with technicals'},
            {'icon': 'fas fa-university',   'title': 'RBI Policy',    'desc': 'Central bank intervention tracking'},
            {'icon': 'fas fa-exchange-alt', 'title': 'Cross Rates',   'desc': 'EUR/INR, GBP/INR, JPY/INR'},
            {'icon': 'fas fa-globe-asia',   'title': 'Global FX',     'desc': 'DXY and emerging market correlations'},
        ],
        'market_hours':   'NSE Currency: 9:00 AM - 5:00 PM IST',
        'signal_type':    'CURRENCY',
        'example_symbols':'USDINR, EURINR, GBPINR',
    },
    'bonds': {
        'name': 'Bonds',
        'title': 'Bonds Research & Signals',
        'subtitle': 'Fixed income analysis for G-Secs and Corporate Bonds',
        'icon': 'fas fa-file-contract',
        'description': 'Yield curve analysis, G-Sec trading signals, and corporate bond recommendations.',
        'features': [
            {'icon': 'fas fa-landmark',    'title': 'G-Sec Analysis',  'desc': 'Government securities yield tracking'},
            {'icon': 'fas fa-chart-line',  'title': 'Yield Curve',     'desc': 'Yield curve shape and movements'},
            {'icon': 'fas fa-building',    'title': 'Corporate Bonds', 'desc': 'Credit rating based recommendations'},
            {'icon': 'fas fa-percentage',  'title': 'Rate Outlook',    'desc': 'RBI rate decision impact analysis'},
        ],
        'market_hours':   'RBI Retail Direct: 9:00 AM - 5:00 PM IST',
        'signal_type':    'BOND',
        'example_symbols':'GSUMSM, GOVT6, GOVT7',
    },
    'mutual_funds': {
        'name': 'Mutual Funds',
        'title': 'Mutual Funds Research & Signals',
        'subtitle': 'Fund analysis, SIP recommendations and portfolio insights',
        'icon': 'fas fa-piggy-bank',
        'description': 'Comprehensive mutual fund research with category comparisons and SIP timing signals.',
        'features': [
            {'icon': 'fas fa-star',     'title': 'Fund Ratings',    'desc': 'Performance-based fund rankings'},
            {'icon': 'fas fa-sync',     'title': 'SIP Timing',      'desc': 'Optimal SIP entry signals'},
            {'icon': 'fas fa-th-large', 'title': 'Category Analysis','desc': 'Sector and thematic fund insights'},
            {'icon': 'fas fa-user-tie', 'title': 'Fund Manager',    'desc': 'Track record and style analysis'},
        ],
        'market_hours':   'AMC: 9:30 AM - 3:00 PM IST (NAV cut-off)',
        'signal_type':    'MF',
        'example_symbols':'HDFCBANK, ICICIBANK, AXISBANK',
    },
}
